In [1]:
import torch

In [2]:
sample = torch.rand(3,2)

In [3]:
sample

tensor([[0.3686, 0.6916],
        [0.2289, 0.9789],
        [0.0717, 0.7710]])

In [4]:
torch.sum(sample)

tensor(3.1107)

In [5]:
torch.min(sample)

tensor(0.0717)

In [6]:
torch.max(sample)

tensor(0.9789)

In [7]:
torch.argmin(sample)

tensor(4)

In [8]:
torch.argmax(sample)

tensor(3)

In [9]:
torch.mean(sample)

tensor(0.5185)

In [10]:
torch.median(sample)

tensor(0.3686)

In [11]:
torch.sqrt(sample)

tensor([[0.6071, 0.8317],
        [0.4784, 0.9894],
        [0.2677, 0.8781]])

In [12]:
sample ** 2

tensor([[0.1359, 0.4784],
        [0.0524, 0.9583],
        [0.0051, 0.5944]])