In [1]:
import torch

In [2]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[3, 2, 3],
        [1, 4, 1]])
tensor([[1, 2, 2],
        [2, 3, 3]])


In [3]:
a+b

tensor([[4, 4, 5],
        [3, 7, 4]])

In [4]:
torch.add(a,b)

tensor([[4, 4, 5],
        [3, 7, 4]])

In [5]:
result = torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[4., 4., 5.],
        [3., 7., 4.]])

In [6]:
a.add_(b)
a

tensor([[4, 4, 5],
        [3, 7, 4]])

In [7]:
a - b

tensor([[3, 2, 3],
        [1, 4, 1]])

In [8]:
a * b

tensor([[ 4,  8, 10],
        [ 6, 21, 12]])

In [9]:
a / b

tensor([[4.0000, 2.0000, 2.5000],
        [1.5000, 2.3333, 1.3333]])

In [10]:
a // b

tensor([[4, 2, 2],
        [1, 2, 1]])

In [11]:
a % b

tensor([[0, 0, 1],
        [1, 1, 1]])

In [12]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
a

tensor([[4, 4, 5],
        [3, 7, 4]])

In [20]:
torch.matmul(a,tensor)

tensor([[13., 13., 13., 13., 13.],
        [14., 14., 14., 14., 14.]])

In [21]:
a = a.float()

In [22]:
a.dtype

torch.float32

In [23]:
torch.matmul(a,tensor)

tensor([[13., 13., 13., 13., 13.],
        [14., 14., 14., 14., 14.]])

In [24]:
a.T

tensor([[4., 3.],
        [4., 7.],
        [5., 4.]])