In [1]:
import torch

In [2]:
tensor = torch.arange(2,14)
print(tensor)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [3]:
print(tensor[2])

tensor(4)


In [5]:
print(tensor[1:4])

tensor([3, 4, 5])


In [6]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [7]:
index = [1,3,4,5,5]

In [9]:
tensor[index]

tensor([3, 5, 6, 7, 7])