In [1]:
import torch

In [2]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3,4)

tensor([[0.8665, 0.6902, 0.4748, 0.8970],
        [0.4532, 0.4177, 0.7803, 0.5569],
        [0.4028, 0.1907, 0.3119, 0.2699]])

In [5]:
torch.randint(0,10,(2,3))

tensor([[4, 5, 7],
        [8, 6, 8]])

In [6]:
torch.randn(3,4)

tensor([[ 1.8307,  0.4639, -0.2012, -1.6961],
        [-0.0910, -0.1695,  0.5859, -0.3473],
        [-0.2154, -1.3242,  0.0275, -0.5124]])

In [7]:
a = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

In [8]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
b=torch.rand_like(a,dtype=float)

In [13]:
b

tensor([[0.4819, 0.6884],
        [0.7195, 0.5152],
        [0.8671, 0.8268]], dtype=torch.float64)

In [15]:
print(b.shape)
print(b.size())

torch.Size([3, 2])
torch.Size([3, 2])


In [17]:
c = b.view(6)

In [18]:
c

tensor([0.4819, 0.6884, 0.7195, 0.5152, 0.8671, 0.8268], dtype=torch.float64)

In [20]:
c.shape

torch.Size([6])

In [22]:
d = b.view(2,3)

In [23]:
d

tensor([[0.4819, 0.6884, 0.7195],
        [0.5152, 0.8671, 0.8268]], dtype=torch.float64)

In [24]:
d = d.reshape(6)

In [25]:
d

tensor([0.4819, 0.6884, 0.7195, 0.5152, 0.8671, 0.8268], dtype=torch.float64)

In [26]:
d[1]

tensor(0.6884, dtype=torch.float64)

In [28]:
d[1].item()

0.6883847464074545

In [29]:
import numpy as np

In [30]:
e = np.array(d)

In [31]:
e

array([0.48186706, 0.68838475, 0.71946176, 0.51523069, 0.86713154,
       0.82683689])

In [33]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [34]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3])